/*
 * This file is generated by jOOQ.
 */
package com.hamawdeh.engineering.data_schema.tables;


import com.hamawdeh.engineering.data_schema.Keys;
import com.hamawdeh.engineering.data_schema.Public;
import com.hamawdeh.engineering.data_schema.tables.records.ItemSerialRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemSerial extends TableImpl<ItemSerialRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.item_serial</code>
     */
    public static final ItemSerial ITEM_SERIAL = new ItemSerial();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ItemSerialRecord> getRecordType() {
        return ItemSerialRecord.class;
    }

    /**
     * The column <code>public.item_serial.id</code>.
     */
    public final TableField<ItemSerialRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.item_serial.code</code>.
     */
    public final TableField<ItemSerialRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(4).nullable(false), this, "");

    /**
     * The column <code>public.item_serial.description</code>.
     */
    public final TableField<ItemSerialRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.item_serial.created</code>.
     */
    public final TableField<ItemSerialRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private ItemSerial(Name alias, Table<ItemSerialRecord> aliased) {
        this(alias, aliased, null);
    }

    private ItemSerial(Name alias, Table<ItemSerialRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.item_serial</code> table reference
     */
    public ItemSerial(String alias) {
        this(DSL.name(alias), ITEM_SERIAL);
    }

    /**
     * Create an aliased <code>public.item_serial</code> table reference
     */
    public ItemSerial(Name alias) {
        this(alias, ITEM_SERIAL);
    }

    /**
     * Create a <code>public.item_serial</code> table reference
     */
    public ItemSerial() {
        this(DSL.name("item_serial"), null);
    }

    public <O extends Record> ItemSerial(Table<O> child, ForeignKey<O, ItemSerialRecord> key) {
        super(child, key, ITEM_SERIAL);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ItemSerialRecord, Integer> getIdentity() {
        return (Identity<ItemSerialRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ItemSerialRecord> getPrimaryKey() {
        return Keys.ITEM_SERIAL_PKEY;
    }

    @Override
    public List<UniqueKey<ItemSerialRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.ITEM_SERIAL_CODE_KEY);
    }

    @Override
    public ItemSerial as(String alias) {
        return new ItemSerial(DSL.name(alias), this);
    }

    @Override
    public ItemSerial as(Name alias) {
        return new ItemSerial(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemSerial rename(String name) {
        return new ItemSerial(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemSerial rename(Name name) {
        return new ItemSerial(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
