# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=eng
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down


volumes:
  database-data: # named volumes can be managed easier using docker-compose