openapi: 3.0.2
info:
  title: Al hawamdeh engening project
  description: "Al hawamdeh engening project"
  termsOfService: http://swagger.io/terms/
  contact:
    email: abdayyad2012@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1-SNAPSHOT
servers:
  - url: http://localhost:8080/api
tags:
  - name: user
    description: Operations about user
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io
  - name: items
    description: operation about items

paths:
  /user:
    post:
      tags:
        - user
      summary: Create user
      description: Create user functionality
      operationId: createUser
      parameters:
        - name: admin_id
          in: header
          required: true
          schema:
            type: integer
      requestBody:
        description: Created user object
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        200:
          description: "add new user to db"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        500:
          description: "system error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        400:
          description: "validation error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-codegen-request-body-name: body

    get:
      summary: get all users
      tags:
        - user
      operationId: getUsers
      responses:
        200:
          description: operation sucessfull
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

  /user/{name}:
    delete:
      tags:
        - user
      description: delete user by name
      operationId: deleteUserByName
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
      responses:
        200:
          description: delete sucussfully
  /login:
    post:
      tags:
        - user
      summary: login
      operationId: loginUser
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/User'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        500:
          description: system error
          content:
            applicatio/json:
              schema:
                $ref: '#/components/schemas/Error'
  /category:
    get:
      tags:
        - items
      summary: get all categories
      operationId: getCategory
      responses:
        200:
          description: get all category objects
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryResponse'
  /type:
    get:
      tags:
        - items
      summary: get items type
      operationId: getTypes
      responses:
        200:
          description: get all items types
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryResponse'
  /item/{type_code}:
    get:
      tags:
        - items
      summary: get items by type code
      operationId: getItemByCode
      parameters:
        - name: type_code
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: get all items that belongs to type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryResponse'
  /order:
    post:
      tags:
        - items
      summary: post order object to db
      operationId: postOrder
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/OrderObject'
      responses:
        200:
          description: return same object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderObject'
    get:
      tags:
        - items
      summary: get orders
      operationId: getOrders
      parameters:
        - in: query
          name: type
          required: false
          schema:
            type: integer
      responses:
        200:
          description: get list of order objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderResponse'
  /order/csv:
    get:
      tags:
        - items
      summary: get orders csv
      operationId: getOrdersCsv
      parameters:
        - in: query
          name: type
          required: false
          schema:
            type: integer
      responses:
        200:
          description: get list of order objects
          content:
            text/csv:
              schema:
                type: string
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          required:
            - 'false'
        username:
          type: string
        password:
          type: string
    Error:
      type: object
      properties:
        msg:
          type: string
    LoginResponse:
      type: object
      properties:
        id:
          type: integer
          required:
            - 'false'
        status:
          type: boolean
    CategoryResponse:
      type: array
      items:
        $ref: '#/components/schemas/SerialObject'
    SerialObject:
      type: object
      properties:
        code:
          type: integer
        description:
          type: string
    OrderObject:
      type: object
      properties:
        item_code:
          type: integer
        category_code:
          type: integer
        name:
          type: string
        role:
          type: string
        phone:
          type: string
        adress:
          type: string
          required:
            - 'false'
        notes:
          type: string
          required:
            - 'false'
    OrderResponse:
      type: object
      properties:
        serial:
          type: string
        name:
          type: string
        role:
          type: string
        phone:
          type: string
        notes:
          type: string
          required:
            - 'false'
        type:
          type: string