/*
 * This file is generated by jOOQ.
 */
package com.hamawdeh.engineering.data_schema;


import com.hamawdeh.engineering.data_schema.tables.Category;
import com.hamawdeh.engineering.data_schema.tables.EngOrder;
import com.hamawdeh.engineering.data_schema.tables.EngUser;
import com.hamawdeh.engineering.data_schema.tables.Item;
import com.hamawdeh.engineering.data_schema.tables.OrderType;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.category</code>.
     */
    public final Category CATEGORY = Category.CATEGORY;

    /**
     * The table <code>public.eng_order</code>.
     */
    public final EngOrder ENG_ORDER = EngOrder.ENG_ORDER;

    /**
     * The table <code>public.eng_user</code>.
     */
    public final EngUser ENG_USER = EngUser.ENG_USER;

    /**
     * The table <code>public.item</code>.
     */
    public final Item ITEM = Item.ITEM;

    /**
     * The table <code>public.order_type</code>.
     */
    public final OrderType ORDER_TYPE = OrderType.ORDER_TYPE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Category.CATEGORY,
            EngOrder.ENG_ORDER,
            EngUser.ENG_USER,
            Item.ITEM,
            OrderType.ORDER_TYPE
        );
    }
}
