/*
 * This file is generated by jOOQ.
 */
package com.hamawdeh.engineering.data_schema;


import com.hamawdeh.engineering.data_schema.tables.EngOrder;
import com.hamawdeh.engineering.data_schema.tables.EngUser;
import com.hamawdeh.engineering.data_schema.tables.Item;
import com.hamawdeh.engineering.data_schema.tables.ItemSerial;
import com.hamawdeh.engineering.data_schema.tables.SubItem;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.eng_order</code>.
     */
    public static final EngOrder ENG_ORDER = EngOrder.ENG_ORDER;

    /**
     * The table <code>public.eng_user</code>.
     */
    public static final EngUser ENG_USER = EngUser.ENG_USER;

    /**
     * The table <code>public.item</code>.
     */
    public static final Item ITEM = Item.ITEM;

    /**
     * The table <code>public.item_serial</code>.
     */
    public static final ItemSerial ITEM_SERIAL = ItemSerial.ITEM_SERIAL;

    /**
     * The table <code>public.sub_item</code>.
     */
    public static final SubItem SUB_ITEM = SubItem.SUB_ITEM;
}
