/*
 * This file is generated by jOOQ.
 */
package com.hamawdeh.engineering.data_schema.tables.records;


import com.hamawdeh.engineering.data_schema.tables.EngOrder;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EngOrderRecord extends UpdatableRecordImpl<EngOrderRecord> implements Record13<Integer, Integer, Integer, String, String, String, String, String, LocalDateTime, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.eng_order.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.eng_order.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.eng_order.item_id</code>.
     */
    public void setItemId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.eng_order.item_id</code>.
     */
    public Integer getItemId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.eng_order.category_id</code>.
     */
    public void setCategoryId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.eng_order.category_id</code>.
     */
    public Integer getCategoryId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.eng_order.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.eng_order.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.eng_order.role</code>.
     */
    public void setRole(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.eng_order.role</code>.
     */
    public String getRole() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.eng_order.phone</code>.
     */
    public void setPhone(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.eng_order.phone</code>.
     */
    public String getPhone() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.eng_order.address</code>.
     */
    public void setAddress(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.eng_order.address</code>.
     */
    public String getAddress() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.eng_order.notes</code>.
     */
    public void setNotes(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.eng_order.notes</code>.
     */
    public String getNotes() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.eng_order.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.eng_order.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>public.eng_order.company</code>.
     */
    public void setCompany(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.eng_order.company</code>.
     */
    public String getCompany() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.eng_order.company_cat</code>.
     */
    public void setCompanyCat(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.eng_order.company_cat</code>.
     */
    public String getCompanyCat() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.eng_order.email</code>.
     */
    public void setEmail(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.eng_order.email</code>.
     */
    public String getEmail() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.eng_order.sec_phone</code>.
     */
    public void setSecPhone(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.eng_order.sec_phone</code>.
     */
    public String getSecPhone() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Integer, Integer, Integer, String, String, String, String, String, LocalDateTime, String, String, String, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Integer, Integer, Integer, String, String, String, String, String, LocalDateTime, String, String, String, String> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return EngOrder.ENG_ORDER.ID;
    }

    @Override
    public Field<Integer> field2() {
        return EngOrder.ENG_ORDER.ITEM_ID;
    }

    @Override
    public Field<Integer> field3() {
        return EngOrder.ENG_ORDER.CATEGORY_ID;
    }

    @Override
    public Field<String> field4() {
        return EngOrder.ENG_ORDER.NAME;
    }

    @Override
    public Field<String> field5() {
        return EngOrder.ENG_ORDER.ROLE;
    }

    @Override
    public Field<String> field6() {
        return EngOrder.ENG_ORDER.PHONE;
    }

    @Override
    public Field<String> field7() {
        return EngOrder.ENG_ORDER.ADDRESS;
    }

    @Override
    public Field<String> field8() {
        return EngOrder.ENG_ORDER.NOTES;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return EngOrder.ENG_ORDER.CREATED;
    }

    @Override
    public Field<String> field10() {
        return EngOrder.ENG_ORDER.COMPANY;
    }

    @Override
    public Field<String> field11() {
        return EngOrder.ENG_ORDER.COMPANY_CAT;
    }

    @Override
    public Field<String> field12() {
        return EngOrder.ENG_ORDER.EMAIL;
    }

    @Override
    public Field<String> field13() {
        return EngOrder.ENG_ORDER.SEC_PHONE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getItemId();
    }

    @Override
    public Integer component3() {
        return getCategoryId();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public String component5() {
        return getRole();
    }

    @Override
    public String component6() {
        return getPhone();
    }

    @Override
    public String component7() {
        return getAddress();
    }

    @Override
    public String component8() {
        return getNotes();
    }

    @Override
    public LocalDateTime component9() {
        return getCreated();
    }

    @Override
    public String component10() {
        return getCompany();
    }

    @Override
    public String component11() {
        return getCompanyCat();
    }

    @Override
    public String component12() {
        return getEmail();
    }

    @Override
    public String component13() {
        return getSecPhone();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getItemId();
    }

    @Override
    public Integer value3() {
        return getCategoryId();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public String value5() {
        return getRole();
    }

    @Override
    public String value6() {
        return getPhone();
    }

    @Override
    public String value7() {
        return getAddress();
    }

    @Override
    public String value8() {
        return getNotes();
    }

    @Override
    public LocalDateTime value9() {
        return getCreated();
    }

    @Override
    public String value10() {
        return getCompany();
    }

    @Override
    public String value11() {
        return getCompanyCat();
    }

    @Override
    public String value12() {
        return getEmail();
    }

    @Override
    public String value13() {
        return getSecPhone();
    }

    @Override
    public EngOrderRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public EngOrderRecord value2(Integer value) {
        setItemId(value);
        return this;
    }

    @Override
    public EngOrderRecord value3(Integer value) {
        setCategoryId(value);
        return this;
    }

    @Override
    public EngOrderRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public EngOrderRecord value5(String value) {
        setRole(value);
        return this;
    }

    @Override
    public EngOrderRecord value6(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public EngOrderRecord value7(String value) {
        setAddress(value);
        return this;
    }

    @Override
    public EngOrderRecord value8(String value) {
        setNotes(value);
        return this;
    }

    @Override
    public EngOrderRecord value9(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public EngOrderRecord value10(String value) {
        setCompany(value);
        return this;
    }

    @Override
    public EngOrderRecord value11(String value) {
        setCompanyCat(value);
        return this;
    }

    @Override
    public EngOrderRecord value12(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public EngOrderRecord value13(String value) {
        setSecPhone(value);
        return this;
    }

    @Override
    public EngOrderRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, String value6, String value7, String value8, LocalDateTime value9, String value10, String value11, String value12, String value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EngOrderRecord
     */
    public EngOrderRecord() {
        super(EngOrder.ENG_ORDER);
    }

    /**
     * Create a detached, initialised EngOrderRecord
     */
    public EngOrderRecord(Integer id, Integer itemId, Integer categoryId, String name, String role, String phone, String address, String notes, LocalDateTime created, String company, String companyCat, String email, String secPhone) {
        super(EngOrder.ENG_ORDER);

        setId(id);
        setItemId(itemId);
        setCategoryId(categoryId);
        setName(name);
        setRole(role);
        setPhone(phone);
        setAddress(address);
        setNotes(notes);
        setCreated(created);
        setCompany(company);
        setCompanyCat(companyCat);
        setEmail(email);
        setSecPhone(secPhone);
    }
}
