/*
 * This file is generated by jOOQ.
 */
package com.hamawdeh.engineering.data_schema.tables.records;


import com.hamawdeh.engineering.data_schema.tables.EngUser;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EngUserRecord extends UpdatableRecordImpl<EngUserRecord> implements Record6<Integer, String, String, LocalDateTime, Integer, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.eng_user.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.eng_user.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.eng_user.user_name</code>.
     */
    public void setUserName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.eng_user.user_name</code>.
     */
    public String getUserName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.eng_user.password</code>.
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.eng_user.password</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.eng_user.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.eng_user.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.eng_user.privilege</code>.
     */
    public void setPrivilege(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.eng_user.privilege</code>.
     */
    public Integer getPrivilege() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.eng_user.active</code>.
     */
    public void setActive(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.eng_user.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, LocalDateTime, Integer, Boolean> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, LocalDateTime, Integer, Boolean> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return EngUser.ENG_USER.ID;
    }

    @Override
    public Field<String> field2() {
        return EngUser.ENG_USER.USER_NAME;
    }

    @Override
    public Field<String> field3() {
        return EngUser.ENG_USER.PASSWORD;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return EngUser.ENG_USER.CREATED;
    }

    @Override
    public Field<Integer> field5() {
        return EngUser.ENG_USER.PRIVILEGE;
    }

    @Override
    public Field<Boolean> field6() {
        return EngUser.ENG_USER.ACTIVE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUserName();
    }

    @Override
    public String component3() {
        return getPassword();
    }

    @Override
    public LocalDateTime component4() {
        return getCreated();
    }

    @Override
    public Integer component5() {
        return getPrivilege();
    }

    @Override
    public Boolean component6() {
        return getActive();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUserName();
    }

    @Override
    public String value3() {
        return getPassword();
    }

    @Override
    public LocalDateTime value4() {
        return getCreated();
    }

    @Override
    public Integer value5() {
        return getPrivilege();
    }

    @Override
    public Boolean value6() {
        return getActive();
    }

    @Override
    public EngUserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public EngUserRecord value2(String value) {
        setUserName(value);
        return this;
    }

    @Override
    public EngUserRecord value3(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public EngUserRecord value4(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public EngUserRecord value5(Integer value) {
        setPrivilege(value);
        return this;
    }

    @Override
    public EngUserRecord value6(Boolean value) {
        setActive(value);
        return this;
    }

    @Override
    public EngUserRecord values(Integer value1, String value2, String value3, LocalDateTime value4, Integer value5, Boolean value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EngUserRecord
     */
    public EngUserRecord() {
        super(EngUser.ENG_USER);
    }

    /**
     * Create a detached, initialised EngUserRecord
     */
    public EngUserRecord(Integer id, String userName, String password, LocalDateTime created, Integer privilege, Boolean active) {
        super(EngUser.ENG_USER);

        setId(id);
        setUserName(userName);
        setPassword(password);
        setCreated(created);
        setPrivilege(privilege);
        setActive(active);
    }
}
