/*
 * This file is generated by jOOQ.
 */
package com.hamawdeh.engineering.data_schema.tables.records;


import com.hamawdeh.engineering.data_schema.tables.Item;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemRecord extends UpdatableRecordImpl<ItemRecord> implements Record5<Integer, Integer, String, Integer, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.item.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.item.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.item.type_id</code>.
     */
    public void setTypeId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.item.type_id</code>.
     */
    public Integer getTypeId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.item.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.item.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.item.code</code>.
     */
    public void setCode(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.item.code</code>.
     */
    public Integer getCode() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.item.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.item.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, String, Integer, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, String, Integer, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Item.ITEM.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Item.ITEM.TYPE_ID;
    }

    @Override
    public Field<String> field3() {
        return Item.ITEM.DESCRIPTION;
    }

    @Override
    public Field<Integer> field4() {
        return Item.ITEM.CODE;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Item.ITEM.CREATED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getTypeId();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public Integer component4() {
        return getCode();
    }

    @Override
    public LocalDateTime component5() {
        return getCreated();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getTypeId();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public Integer value4() {
        return getCode();
    }

    @Override
    public LocalDateTime value5() {
        return getCreated();
    }

    @Override
    public ItemRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ItemRecord value2(Integer value) {
        setTypeId(value);
        return this;
    }

    @Override
    public ItemRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ItemRecord value4(Integer value) {
        setCode(value);
        return this;
    }

    @Override
    public ItemRecord value5(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public ItemRecord values(Integer value1, Integer value2, String value3, Integer value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemRecord
     */
    public ItemRecord() {
        super(Item.ITEM);
    }

    /**
     * Create a detached, initialised ItemRecord
     */
    public ItemRecord(Integer id, Integer typeId, String description, Integer code, LocalDateTime created) {
        super(Item.ITEM);

        setId(id);
        setTypeId(typeId);
        setDescription(description);
        setCode(code);
        setCreated(created);
    }
}
