/*
 * This file is generated by jOOQ.
 */
package com.hamawdeh.engineering.data_schema.tables.records;


import com.hamawdeh.engineering.data_schema.tables.SubItem;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubItemRecord extends UpdatableRecordImpl<SubItemRecord> implements Record5<Integer, Integer, String, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.sub_item.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.sub_item.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.sub_item.item_id</code>.
     */
    public void setItemId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.sub_item.item_id</code>.
     */
    public Integer getItemId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.sub_item.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.sub_item.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.sub_item.code</code>.
     */
    public void setCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.sub_item.code</code>.
     */
    public String getCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.sub_item.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.sub_item.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, String, String, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, String, String, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return SubItem.SUB_ITEM.ID;
    }

    @Override
    public Field<Integer> field2() {
        return SubItem.SUB_ITEM.ITEM_ID;
    }

    @Override
    public Field<String> field3() {
        return SubItem.SUB_ITEM.DESCRIPTION;
    }

    @Override
    public Field<String> field4() {
        return SubItem.SUB_ITEM.CODE;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return SubItem.SUB_ITEM.CREATED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getItemId();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public String component4() {
        return getCode();
    }

    @Override
    public LocalDateTime component5() {
        return getCreated();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getItemId();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public String value4() {
        return getCode();
    }

    @Override
    public LocalDateTime value5() {
        return getCreated();
    }

    @Override
    public SubItemRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public SubItemRecord value2(Integer value) {
        setItemId(value);
        return this;
    }

    @Override
    public SubItemRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public SubItemRecord value4(String value) {
        setCode(value);
        return this;
    }

    @Override
    public SubItemRecord value5(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public SubItemRecord values(Integer value1, Integer value2, String value3, String value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SubItemRecord
     */
    public SubItemRecord() {
        super(SubItem.SUB_ITEM);
    }

    /**
     * Create a detached, initialised SubItemRecord
     */
    public SubItemRecord(Integer id, Integer itemId, String description, String code, LocalDateTime created) {
        super(SubItem.SUB_ITEM);

        setId(id);
        setItemId(itemId);
        setDescription(description);
        setCode(code);
        setCreated(created);
    }
}
